version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-2048
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: bishant
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: game2048
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: php-2048
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: bishant
      DB_NAME: game2048

volumes:
  mysql-data:
