version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-2048
    restart: unless-stopped
    environment:
      # These values come from your .env file — DO NOT hardcode secrets here
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: php-2048
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"  # Access app at http://localhost:8080
    volumes:
      - .:/var/www/html
    environment:
      # These are used by your PHP app via getenv() in config.php
      DB_HOST: ${DB_HOST}         # Usually 'db' (matches service name)
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  mysql-data:
